version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    container_name: elasticsearch
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: elasticsearch
      bootstrap.memory_lock: "true"
      cluster.name: "docker-cluster"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch
